### ISSUE TITLE
`spago docs` not working with `"type": "module"`

### ISSUE THREAD

**Issue by keijokapp** [purescript/spago#949]
`"type": "module"` setting in `package.json` is very common nowadays. But with that option, `spago docs` fails with the following output:
```
[info] Generating documentation for the project. This might take a while...
Documentation written to: generated-docs/html
[info] Docs generation succeeded.
[info] Making the documentation searchable...
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension "" for /path/to/project/.spago/purescript-docs-search. Loading extensionless files is not supported inside of "type":"module" package.json contexts. The package.json file /home/keijo/projects/tank/package.json caused this "type":"module" context. Try changing /path/to/project/.spago/purescript-docs-search to have a file extension. Note the "bin" field of package.json can point to a file with an extension, for example {"type":"module","bin":{"purescript-docs-search":"./.spago/purescript-docs-search.js"}}
    at new NodeError (node:internal/errors:399:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:74:9)
    at defaultGetFormat (node:internal/modules/esm/get_format:114:38)
    at defaultLoad (node:internal/modules/esm/load:81:20)
    at nextLoad (node:internal/modules/esm/loader:163:28)
    at ESMLoader.load (node:internal/modules/esm/loader:597:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:449:22)
    at new ModuleJob (node:internal/modules/esm/module_job:63:26)
    at #createModuleJob (node:internal/modules/esm/loader:472:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:426:34) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}

Node.js v19.7.0
[warn] Failed while trying to make the documentation searchable: 1
[info] Link: file:///path/to/project/generated-docs/html/index.html
```

There seems to be two possible solutions:
1. Add `.cjs` file extension to `purescript-docs-search`. It seems to work all the way down to Node v10.
2. Make `purescript-docs-search` script use native ESM (requires Node 14+) and and add `.mjs` file extension.

I'm willing to make a PR.

**Comment by f-f** [comment]
Thanks for reporting @keijokapp!

I marked this as a bug because it's just broken and should be fixed - however the current Haskell codebase is basically frozen because we are porting it to PureScript.
You can install the pre-alpha of the port with `npm i spago@next` if you'd like to try it and you can find the source [here](https://github.com/purescript/spago/tree/master/spaghetto).

The timeline for this to become the main version is quite short, as we aim to bless an alpha release in the next weeks. However this new version doesn't yet have a `docs` command.
It should be easier to avoid these issues because we can just bundle the source all together, since it's all JS now and we don't have to call an external process - would you like to make a PR for this new implementation instead of patching the Haskell codebase?

**Comment by keijokapp** [comment]
I haven't had a chance to look at the new Spago yet. I will try it out asap and maybe find something to work on. I would assume that the PS/JS-based implementation doesn't have that problem because of the reasons you describe.

The issue doesn't really affect me that much. If the current codebase is frozen and is going to be retired soon, I guess it's not worth fixing right now. The issue could stay open for others.

**Comment by silky** [comment]
@f-f - Any update on this one? I'm still getting this error; taking `spago` from the latest commit of `easy-purescript-nix` ...

**Comment by f-f** [comment]
@silky nothing has changed from my latest comment, except that we are now approximately one week away from the new release 😄

After that's out I'll be able to look at that, but in the meantime I'd still appreciate any help to make this happen more quickly.
Let me know if you are interested, and if so I could detail further on the steps that are needed to move this forward!

**Comment by thought2** [comment]
It seems to be the `package.json` inside `.spago` causing the issue.

I just use this to remove the "module" type before running `spago docs` and re-add it afterwards. :)

`FILE=.spago/package.json; echo '{}' > $FILE; spago docs; echo '{"type": "module"}' > $FILE`

**Comment by f-f** [comment]
I'll close this issue, as we are finally porting `spago docs` to work natively with the new Spago. That one is tracked in #1020, so please refer to that one for updates on the new integration.
